/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class pers_dll_infc_JavaInvokeCPlus */

#ifndef _Included_pers_dll_infc_JavaInvokeCPlus
#define _Included_pers_dll_infc_JavaInvokeCPlus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_dll_infc_JavaInvokeCPlus
 * Method:    Init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_pers_dll_infc_JavaInvokeCPlus_Init
  (JNIEnv *, jobject);

/*
 * Class:     pers_dll_infc_JavaInvokeCPlus
 * Method:    InitNewCon
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_pers_dll_infc_JavaInvokeCPlus_InitNewCon
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     pers_dll_infc_JavaInvokeCPlus
 * Method:    InitNewDatafromDst
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_pers_dll_infc_JavaInvokeCPlus_InitNewDatafromDst
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     pers_dll_infc_JavaInvokeCPlus
 * Method:    InitNewDatafromSource
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_pers_dll_infc_JavaInvokeCPlus_InitNewDatafromSource
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     pers_dll_infc_JavaInvokeCPlus
 * Method:    InitClose
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_pers_dll_infc_JavaInvokeCPlus_InitClose
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     pers_dll_infc_JavaInvokeCPlus
 * Method:    InitNewConData
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_pers_dll_infc_JavaInvokeCPlus_InitNewConData
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     pers_dll_infc_JavaInvokeCPlus
 * Method:    SuspendRecv
 * Signature: (IZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_pers_dll_infc_JavaInvokeCPlus_SuspendRecv
  (JNIEnv *, jobject, jint, jboolean, jboolean);

/*
 * Class:     pers_dll_infc_JavaInvokeCPlus
 * Method:    SetInterceptStatus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_pers_dll_infc_JavaInvokeCPlus_SetInterceptStatus
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     pers_dll_infc_JavaInvokeCPlus
 * Method:    SayHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pers_dll_infc_JavaInvokeCPlus_SayHelloWorld
  (JNIEnv *, jobject);

/*
 * Class:     pers_dll_infc_JavaInvokeCPlus
 * Method:    AddSendtoDstBuffer
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_pers_dll_infc_JavaInvokeCPlus_AddSendtoDstBuffer
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     pers_dll_infc_JavaInvokeCPlus
 * Method:    AddSendtoSourceBuffer
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_pers_dll_infc_JavaInvokeCPlus_AddSendtoSourceBuffer
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     pers_dll_infc_JavaInvokeCPlus
 * Method:    StartServer
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_pers_dll_infc_JavaInvokeCPlus_StartServer
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     pers_dll_infc_JavaInvokeCPlus
 * Method:    StopServer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_pers_dll_infc_JavaInvokeCPlus_StopServer
  (JNIEnv *, jobject);

/*
 * Class:     pers_dll_infc_JavaInvokeCPlus
 * Method:    SuspendServer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_pers_dll_infc_JavaInvokeCPlus_SuspendServer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
